[project]
name = "afden-python-workshop"
version = "2025.09.24"
description = "Python Coding for Accounting and Finance Research. See https://www.afaanz.org/doctoral-education for details."
readme = "README.md"
requires-python = ">=3.12.10"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.5",
    "nest-asyncio>=1.6.0",
    "nltk>=3.9.1",
    "openai>=1.106.1",
    "pandas>=2.2",
    "python-dotenv>=1.1.1",
    "regex>=2025.7.34",
    "regpyhdfe>=0.0.10",
    "requests>=2.32.5",
    "seaborn>=0.13.2",
    "secedgar>=0.6.0",
    "textstat>=0.7.8",
    "wrds>=3.4.0",
]
